### ISSUE TITLE
Should I install it?

### ISSUE THREAD

**Issue by antonio-petricca** [Syniurge/i2c-amd-mp2#13]
Hi, I have a Dell 5495, equipped with Linux Mint (Ubuntu 18.04), and kernel from **4.15.0-65-generic** up to **4.18.0-25-generic**.

Very often I have to touch two times the touchpad in order to get it activated (the first time the mouse pointer does not move).

Is that issue addressed and fixed by your driver?

Thank yoy so much!
Antonio

**Comment by Syniurge** [comment]
No this is the same driver as the one backported in 4.15.0-65-generic.

Maybe give a newer kernel a try, a 5.2 or 5.3 from https://kernel.ubuntu.com/~kernel-ppa/mainline/ (most of the testing was done on newer kernels)

> Very often I have to touch two times the touchpad in order to get it activated (the first time the mouse pointer does not move).

How much time does the pointer stay frozen?

**Comment by antonio-petricca** [comment]
![image](https://user-images.githubusercontent.com/6660386/67127034-c7eea500-f1f8-11e9-8bf7-454f630e2a7d.png)

As you stated, and as you can see by the above image, I have that driver installed.

I want to show you my scenario:

1. I put my finger on the touchpad.
2. I try to move the pointer.
3. The pointer stucks and it does not move.
4. I remove my finger from the touchpad.
5. I put down my finger again.
6. The pointer now moves on.

It happens more the 50% times! It is very annoying! :(

**PS:** I cannot use kernels newer then 4.17 because the **Pulse Secure Client** does not work since 4.18, and I need it for my daily work.

**Comment by antonio-petricca** [comment]
I have just received a the latest Pulse Client release, working on 5.0.0 too.

On that kernel the touchpad seems to work as expected.

Thank you so much for your attention.

**Comment by antonio-petricca** [comment]
I would inform that, with a lower frequency, but the described issue is still present with kernel 5.0.0.

**Comment by Syniurge** [comment]
Does any error show up in dmesg?

And if you installed it from an official Ubuntu package, this is still a backported driver and the kernel might contain other Ubuntu-specific changes affecting it, could you try the latest "vanilla/mainline" 5.2.21 kernel from the previous link just to check if the issue is still here?

**Comment by antonio-petricca** [comment]
Solved by unchecking "Disable touchpad while typing". 

Thank you anyway. :)
