### ISSUE TITLE
Mainline status?

### ISSUE THREAD

**Issue by MrDrMcCoy** [Syniurge/i2c-amd-mp2#8]
This driver was essential in getting the touchpad to work properly with my AMD Lenovo laptop and works quite well for me. I was just wondering how far along discussions are for getting this merged upstream so that we don't have to finagle with DKMS when reinstalling or testing out new kernel versions. Thank you so much for your hard work!

**Comment by Syniurge** [comment]
It's been pulled last week into the i2c subsystem maintainers' tree, so it should be pulled into Linux 5.2 during the merge window (a few days after 5.1 gets released).

**Comment by MrDrMcCoy** [comment]
Wonderful! I really appreciate the update :)
